/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/personal-info`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/doctorHome` | `/doctorHome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/oldPatientIndex` | `/oldPatientIndex`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/patientDisplay` | `/patientDisplay`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/patientHome` | `/patientHome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/prescribe` | `/prescribe`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/prescriptions` | `/prescriptions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/misc/scan`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/personal-info`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/doctorHome` | `/doctorHome`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/oldPatientIndex` | `/oldPatientIndex`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/patientDisplay` | `/patientDisplay`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/patientHome` | `/patientHome`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/prescribe` | `/prescribe`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/prescriptions` | `/prescriptions`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/misc/scan`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/personal-info${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/doctorHome${`?${string}` | `#${string}` | ''}` | `/doctorHome${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/oldPatientIndex${`?${string}` | `#${string}` | ''}` | `/oldPatientIndex${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/patientDisplay${`?${string}` | `#${string}` | ''}` | `/patientDisplay${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/patientHome${`?${string}` | `#${string}` | ''}` | `/patientHome${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/prescribe${`?${string}` | `#${string}` | ''}` | `/prescribe${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/prescriptions${`?${string}` | `#${string}` | ''}` | `/prescriptions${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/misc/scan${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/personal-info`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/doctorHome` | `/doctorHome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/oldPatientIndex` | `/oldPatientIndex`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/patientDisplay` | `/patientDisplay`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/patientHome` | `/patientHome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/prescribe` | `/prescribe`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/prescriptions` | `/prescriptions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/misc/scan`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
